// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustGo.Models
{
    public partial class ScheduleDetails
    {
        public int ScheduleId { get; set; }
        public int DetailsId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndtTime { get; set; }
        public int PlaceId { get; set; }
        public string Town { get; set; }
        public bool? WeatherWarning { get; set; }
        public int? Pop { get; set; }
        public int? Temperature { get; set; }
        public int? Uvi { get; set; }

        public virtual Schedule Schedule { get; set; }
    }
}