// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustGo.Models
{
    public partial class UserKeep
    {
        public int KeepId { get; set; }
        public string UserId { get; set; }
        public int KeepClass { get; set; }
        public int KeepNumber { get; set; }
    }
}