// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustGo.Models
{
    public partial class Blog
    {
        public Blog()
        {
            BlogDetails = new HashSet<BlogDetails>();
        }

        public int BlogId { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string Describe { get; set; }
        public string ImageName { get; set; }
        public int? Like { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public virtual ICollection<BlogDetails> BlogDetails { get; set; }
    }
}