// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace JustGo.Models
{
    public partial class BlogDetails
    {
        [Key]
        public int DetailsId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndtTime { get; set; }
        public int PlaceId { get; set; }
        public string Describe { get; set; }
        public string Images { get; set; }
        public double? Score { get; set; }
        public int? BlogId { get; set; }

        public virtual Blog Blog { get; set; }
    }
}