// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace JustGo.Models
{
    public partial class fn_selePlaceDistanceResult
    {
        public int PlaceID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Tel { get; set; }
        public string Add { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public string Region { get; set; }
        public string Town { get; set; }
        public int Class { get; set; }
        public string Opentime { get; set; }
        public int? intOpentime { get; set; }
        public string Closetime { get; set; }
        public int? intClosetime { get; set; }
        public int? Timestay { get; set; }
    }
}
