// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustGo.Models
{
    public partial class Place
    {
        public string PlaceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Tel { get; set; }
        public string Add { get; set; }
        public double Px { get; set; }
        public double Py { get; set; }
        public string Region { get; set; }
        public string Town { get; set; }
        public int? Class { get; set; }
        public string Opentime { get; set; }
        public string Closetime { get; set; }
        public int? Timestay { get; set; }
    }
}