// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustGo.Models
{
    public partial class Schedule
    {
        public Schedule()
        {
            ScheduleDetails = new HashSet<ScheduleDetails>();
        }

        public int ScheduleId { get; set; }
        public int UserId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool? WeatherWarning { get; set; }

        public virtual ICollection<ScheduleDetails> ScheduleDetails { get; set; }
    }
}