// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using JustGo.Models;

namespace JustGo.Models
{
    public partial class TravelContext
    {

        [DbFunction("fn_seleFoodDistance", "dbo")]
        public IQueryable<fn_seleFoodDistanceResult> fn_seleFoodDistance(double? MyPx, double? MyPy, double? SeleDis)
        {
            return FromExpression(() => fn_seleFoodDistance(MyPx, MyPy, SeleDis));
        }

        [DbFunction("fn_seleHotelDistance", "dbo")]
        public IQueryable<fn_seleHotelDistanceResult> fn_seleHotelDistance(double? MyPx, double? MyPy, double? SeleDis)
        {
            return FromExpression(() => fn_seleHotelDistance(MyPx, MyPy, SeleDis));
        }

        [DbFunction("fn_seleSpotDistance", "dbo")]
        public IQueryable<fn_seleSpotDistanceResult> fn_seleSpotDistance(double? MyPx, double? MyPy, double? SeleDis)
        {
            return FromExpression(() => fn_seleSpotDistance(MyPx, MyPy, SeleDis));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_seleFoodDistanceResult>().HasNoKey();
            modelBuilder.Entity<fn_seleHotelDistanceResult>().HasNoKey();
            modelBuilder.Entity<fn_seleSpotDistanceResult>().HasNoKey();
        }
    }
}
