// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using JustGo.Models;

namespace JustGo.Models
{
    public partial class TravelContext
    {

        [DbFunction("fn_selePlaceDistance", "dbo")]
        public IQueryable<fn_selePlaceDistanceResult> fn_selePlaceDistance(double? Mylat, double? Mylng, double? SeleDis)
        {
            return FromExpression(() => fn_selePlaceDistance(Mylat, Mylng, SeleDis));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_selePlaceDistanceResult>().HasNoKey();
        }
    }
}
