// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JustGo.Models
{
    public partial class Weather
    {
        public string Location { get; set; }
        public string LocationsName { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? Pop12h { get; set; }
        public int? MinT { get; set; }
        public int? MaxT { get; set; }
        public int? Uvi { get; set; }
        public string Wx { get; set; }
        public string WeatherDescription { get; set; }
    }
}